[package]
name = "stellar-contract-explorer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "stellar-contract-explorer"
path = "src/main.rs"

[dependencies]
promkit = "=0.6.2"
anyhow = "1.0.95"
log = "0.4.25"
serde_json = "1.0.137"
